name: tabwa_french
description: A tabwa french collective dictionary

publish_to: 'none'

version: 1.0.17+17

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  fluttericon: ^2.0.0
  google_fonts: ^2.3.2

  path_provider: ^2.0.9
  get: ^4.6.1
  get_storage: ^2.0.3
  fl_toast: ^3.1.0
  smirl_version_checker: ^0.0.1
  package_info_plus: ^1.0.4
  fluttertoast: ^8.0.9

  # record and play audio
  flutter_sound_lite: ^8.5.0

  # file permissions
  permission_handler: ^9.2.0

  # connectivity
  connectivity_plus: ^2.2.1

  # adding badge to widget
  badges: ^2.0.2
  easy_table: ^1.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  msix: ^3.6.2

flutter:

  uses-material-design: true

msix_config:
  display_name: Dictionnaire Tabwa-Français
  publisher_display_name: francis N Numbi
  publisher: CN=004404043FFIR-4DDUEHFKD-DLDK4L3L
  identity_name: org.smirl.tabwa-french
  msix_version: 1.0.0.0
  logo_path: C:\Projects\dart_flutters\tabwa_french\android\app\src\main\res\mipmap\ic_launcher.png
  icons_background_color: "#ffffff"
  architecture: x64
  publisher_url: https://tabwa.smirltech.com/applications
  publisher_email: francis@smirltech.com
  publisher_website: https://tabwa.smirltech.com/applications
  publisher_logo: https://tabwa.smirltech.com/applications/images/logo.png
  # some comments
  # capabilities: "internetClient"
  capabilities: internetClient, microphone

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
